### ISSUE TITLE
checksum

### ISSUE THREAD

**Issue by mtaich1** [cisagov/CHIRP#11]
# 💡 Summary #

Would you please provide chirp.exe checksum?
## Motivation and context ##

Why does this work belong in this project?

This would be useful because...

## Implementation notes ##

Please provide details for implementation, such as:

- an example for how this would be used
- what this would look like
- how this would act
- any related work, including links to related issues

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Criterion

**Comment by DeemOnSecurity** [comment]
We will work on implementing hashing in our CI. Thank you for the input!

**Comment by mtaich1** [comment]
Will,

Thank you for doing this!  I would suggest, though, to remove leading 17 characters from the paths in the hashes.csv, I think users should not see this. Besides, if you push "...\CHIRP\chirp.exe" file to the repository, why would you include in the hashes.csv "...\CHIRP\chirp.dist\chirp.exe" as well? Maybe I'm just missing something...

Thanks,
Michael


Will,

My pleasure.

From: Will Deem ***@***.***>
Sent: Friday, March 19, 2021 12:05 PM
To: cisagov/CHIRP ***@***.***>
Cc: Taich, Michael B. (GRC-VE00)[DB Consulting Group, Inc.] ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [cisagov/CHIRP] checksum (#11)


We will work on implementing hashing in our CI. Thank you for the input!

-
