### ISSUE TITLE
Other python project with name Chirp already registered as package

### ISSUE THREAD

**Issue by ivbeg** [cisagov/CHIRP#19]
# 🐛 Summary #

Other Chirp project for Python already exists and it's registered as Python package.

## To reproduce ##

Open PyPi package https://pypi.org/project/chirp/

## Expected behavior ##

I would expect that if project has unique name.

**Comment by DeemOnSecurity** [comment]
This program is written in python but has no intention of being used as a python package or being uploaded to PYPI, the CISA Hunt and Incident Response Program also as no overlap in its capabilities. There should be no need to rename the program.
