### ISSUE TITLE
Setup File reputation is malicious!!?? 

### ISSUE THREAD

**Issue by Elektra-10** [cisagov/CHIRP#27]
Downloaded the latest version>unzipped>sandboxed the chirp.exe

Reports of being Malicious.
- Open source sandboxing tool - cuckoo sandbox
- and even VirusTotal in some cases

Does anyone verified it before running in their environment?

**Comment by DeemOnSecurity** [comment]
We access every file on the system for analysis, which is pretty suspicious to AVs that use heuristic detection. There is nothing we can do to prevent our program being flagged (yes, even code signing) and in some cases the executable must be whitelisted to bypass AV.
