### ISSUE TITLE
Exception Processing Message

### ISSUE THREAD

**Issue by bneu78** [cisagov/CHIRP#37]
# 🐛 Summary #

When running chirp.exe with defaults this error comes up multiple times even when hitting continue. 

I ran chirp.exe from the extract folder of chirp running from C:\chirp\

![Screenshot from 2021-04-08 19-02-49](https://user-images.githubusercontent.com/3135208/114110519-52b7d980-989d-11eb-8949-dab18dbccad2.png)

**Comment by DeemOnSecurity** [comment]
Good evening,

 I will require more information about your environment to troubleshoot this.

 - What is the Windows version you are running?
 - What version of CHIRP are you running?
 - Does this error happen when double clicking the binary? Running from the command line? 
 - Are you running as admin?

**Comment by bneu78** [comment]
I should be ashamed of myself, should have posted that initially. Sorry about that, here goes:
Windows version:
![image](https://user-images.githubusercontent.com/3135208/114620800-8f0a8180-9c71-11eb-84fd-2620115bcb19.png)

CHIRP version 1.0.5

Error happens when running binary from cmd or double clicking.

Yes, running as admin.

**Comment by DeemOnSecurity** [comment]
Few more questions. 

- What steps are you following to get this error output? (Download to run)
- Are you downloading the zip from the releases tab in the repository then unzipping and running from the main drive of the server?

I apologize, this specific error code does not have any useful results in technet or Microsoft's documentation

**Comment by DeemOnSecurity** [comment]
> Few more questions.
> 
>     * What steps are you following to get this error output? (Download to run)
> 
>     * Are you downloading the zip from the releases tab in the repository then unzipping and running from the main drive of the server?
> 
> 
> I apologize, this specific error code does not have any useful results in technet or Microsoft's documentation

This does appear to have to do with a removable drive, is there a removable drive like a CD or USB plugged in to the server? Possibly our enumeration of drives is causing the issue 🤔

**Comment by DeemOnSecurity** [comment]
Maybe this helps: http://windowsbulletin.com/how-to-fix-windows-no-disk-exception-processing-message-c0000013/

**Comment by bneu78** [comment]
I'm going to write it off as a annoying Microsoft thing, it works on the clients other servers just fine. Thanks for your help. I'm closing this issue.
