### ISSUE TITLE
Uncaught exception in events plugin. FileNotFound error if eventlog not present.

### ISSUE THREAD

**Issue by PowerShellMike** [cisagov/CHIRP#5]
# 🐛 Summary #

CHIRP stops running on server between 450000 and 500000 files processed.

## To reproduce ##

1. Download CHIRP.zip from "Releases"
2. Extract all to C:\Temp\CHIRP
3. Run chirp as administrator
4. It starts, but eventually stops processing.

I noticed CPU usage reduces to nothing across all CHIRP processes. Let it sit for about 3 hours and no progress. Pressing "Enter" key gives traceback error and the process dies.

## Expected behavior ##

Expected process to complete successfully.

## Any helpful log output or screenshots ##

![CHIRP](https://user-images.githubusercontent.com/26772135/111715393-19ee8c80-882a-11eb-8d8c-b978a2ab5e2f.PNG)

**Comment by DeemOnSecurity** [comment]
Ah, this appears to be an uncaught exception in our events plugin (it's asynchronous code, so the events plugin was running in the background). I will try to have a fix for this out soon.
