### ISSUE TITLE
Program freezes after scan complete

### ISSUE THREAD

**Issue by DeemOnSecurity** [cisagov/CHIRP#8]
# 🐛 Summary #

CHIRP should print it has completed then runs input() to hold the window until a user presses another button, however the process hangs after all scans have completed.

## To reproduce ##

1. Run chirp.exe

## Expected behavior ##

CHIRP should only hang until a key is pressed.

## Any helpful log output or screenshots ##

Add any screenshots of the problem here.
![image](https://user-images.githubusercontent.com/19997347/111724181-2deeba00-883b-11eb-917d-81f643f2f989.png)

**Comment by DASCert** [comment]
"Expected behavior"
CHIRP should only hang until a key is pressed.??

Really?  If the purpose is to hold the window open, assuming that someone double-clicked the exe to run it, a "process complete, press any key to close" message would be nice,  As it is, the process hangs before it actually complete (see Issue #10)

**Comment by DeemOnSecurity** [comment]
> "Expected behavior"
> CHIRP should only hang until a key is pressed.??
> 
> Really? If the purpose is to hold the window open, assuming that someone double-clicked the exe to run it, a "process complete, press any key to close" message would be nice, As it is, the process hangs before it actually complete (see Issue #10)

In the case of issue #10, the process never completed as an exception was thrown by the events plugin on the main process. The extra workers running were still running the yara scan. 

You're right that we should consider adding the "Press Any Key" verbiage to the done message, but we still need to figure out how to get it to quit once a key is pressed or it's a moot point 😄.

**Comment by DeemOnSecurity** [comment]
Resolved by #12
